/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorDetail { 
    /**
     * Where the error occurred, e.g. \'body.items[3].tags\' or \'path.thing-id\'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    value?: any | null;
}

