/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Task { 
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    createdDate: string;
    description: string;
    id: number;
    rank: number;
    snoozedUntil: string;
    status: string;
    taskID: string;
    title: string;
    update: string;
}

