/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskUpdate } from './taskUpdate';
import { Task } from './task';


export interface TaskSummary { 
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    task: Task;
    updates: Array<TaskUpdate> | null;
}

