/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskUpdate } from './taskUpdate';
import { Task } from './task';


export interface TaskWeeklySummary { 
    task: Task;
    updates: Array<TaskUpdate> | null;
}

