/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateRecurringTaskInputBody { 
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    freqByWeekDay: string;
    taskDescription: string;
    taskTitle: string;
}

