/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Entry { 
    createdDate: string;
    description: string;
    id: number;
    rank: number;
    recurringTaskID: number;
    status: string;
    taskID: string;
    taskSnoozedUntil: string;
    taskUpdate: string;
    title: string;
}

