/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Entry } from './entry';


export interface ListEntriesResponse { 
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    done: Array<Entry> | null;
    pending: Array<Entry> | null;
}

