/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetTaskDoneInputBody { 
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * If task should be set as done or not
     */
    done: boolean;
}

