/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskUpdate } from './taskUpdate';
import { Entry } from './entry';


export interface TaskSummary { 
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    taskEntry: Entry;
    updates: Array<TaskUpdate> | null;
}

