/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Entry } from './entry';
import { TaskSummary } from './taskSummary';


export interface WeeklySummary { 
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    Notes: Array<Entry> | null;
    TaskSummaries: Array<TaskSummary> | null;
}

